### ISSUE TITLE
9.6-2.3 postgis failing on arm

### ISSUE THREAD

**Issue by dbussert** [Tob1as/docker-postgresql-postgis#2]
`docker inspect tobi312/rpi-postgresql-postgis:9.6-2.3`, SHA is `sha256:16ad1f872c87293f8db373911bbc02d83a7714979ab5cd33fdbf07d6b316426b`

Result is

```
apex=# SELECT PostGIS_version();
ERROR:  function postgis_version() does not exist
LINE 1: SELECT PostGIS_version();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by dbussert** [comment]
tied to this issue with the entrypoint that install postgis 

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/10_postgis.sh
/docker-entrypoint-initdb.d/10_postgis.sh: line 12: syntax error: bad substitution
```

**Comment by Tob1as** [comment]
I have now copied the scripts directly from the orginal postgis image and fixed the error.

But 9.6 Image based on Debian 9, both are end of life, see https://endoflife.date/
